<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\Course;
use App\Models\Expert;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Sequence;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->expertSeed()
        ->courseSeed();

        for ($i = 0; $i < 1; $i++) {
            $this->userSeed();
        }

        // $scores = collect(['A', 'A-', 'B+', 'B', 'B-'/* , 'C+', 'C' *//* , 'D', 'E' */]);
        // $randomScores = collect(['A', 'A-', 'B+', 'B', 'B-', 'C+', 'C'/* , 'D', 'E' */]);

        // $courses = Course::query()->get();
        // $random = (int) round(.15 * $courses->count());

        /* User::factory(40)->create()
        ->each(function (User $user) use ($scores, $randomScores, $courses, $random) {
            $user->courses()->sync(
                $courses->shuffle()->mapWithKeys(fn (Course $course, int $iterate) => [
                    $course->id => ['score' => $iterate < $random ? $randomScores->random() : $scores->random()],
                ])
            );
        }); */

        // $this->command->info('Finish seeding users');
    }

    private function expertSeed(): self
    {
        Expert::query()->insert([[
            'name' => 'Knowledge Engineering & Data Science',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'name' => 'Ubiquitos Computing',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'name' => 'Game Technology & Machine Learning Applications',
            'created_at' => now(),
            'updated_at' => now(),
        ]]);

        $this->command->info('Finish seeding experts');

        return $this;
    }

    private function courseSeed(): self
    {
        collect([
            ['name' => 'Bahasa Inggris Profesi', 'kbk' => [1, 2, 3]],
            ['name' => 'Kesehatan dan Keselamatan Kerja (K3)', 'kbk' => [1, 2, 3]],
            ['name' => 'Matematika Komputer 1', 'kbk' => [1, 2, 3]],
            ['name' => 'Pengantar Teknologi Informasi', 'kbk' => [1, 2, 3]],
            ['name' => 'Algoritma dan Pemrograman', 'kbk' => [1, 2, 3]],
            ['name' => 'Basis Data dan Sistem Informasi', 'kbk' => [1, 2, 3]],
            ['name' => 'Organisasi dan Arsitektur Komputer', 'kbk' => [1, 2, 3]],
            ['name' => 'Matematika Komputer 2', 'kbk' => [1, 2, 3]],
            ['name' => 'Pemrograman Berorientasi Obyek', 'kbk' => [1, 2, 3]],
            ['name' => 'Komunikasi Data dan Jaringan Komputer', 'kbk' => [2]],
            ['name' => 'Struktur Data', 'kbk' => [1, 2, 3]],
            ['name' => 'Probabilitas dan Statistik', 'kbk' => [1]],
            ['name' => 'Pemrograman Web', 'kbk' => [1, 2, 3]],
            ['name' => 'Matematika Komputer 3', 'kbk' => [1, 2, 3]],
            ['name' => 'Rekayasa Perangkat Lunak', 'kbk' => [1, 2, 3]],
            ['name' => 'Sistem Operasi', 'kbk' => [1, 2, 3]],
            ['name' => 'Grafika Komputer', 'kbk' => [3]],
            ['name' => 'Pemrograman Deklaratif', 'kbk' => [1, 2, 3]],
            ['name' => 'Interaksi Manusia dan Komputer', 'kbk' => [1, 2, 3]],
            ['name' => 'Multimedia', 'kbk' => [3]],
            ['name' => 'Proyek Sistem Informasi', 'kbk' => [1, 2, 3]],
            ['name' => 'Analisis dan Desain Algoritma', 'kbk' => [1, 2, 3]],
            ['name' => 'Sosioteknologi Informatika', 'kbk' => [1, 2, 3]],
            ['name' => 'Keamanan Jaringan & Kriptografi', 'kbk' => [3]],
            ['name' => 'Kecerdasan Buatan', 'kbk' => [2]],
            ['name' => 'Internet of things (IoT)', 'kbk' => [2]],
            ['name' => 'Educational Informatics', 'kbk' => [3]],
            ['name' => 'Metodologi Penelitian', 'kbk' => [1, 2, 3]],
            ['name' => 'Kewirausahaan', 'kbk' => [1, 2, 3]],
            ['name' => 'Game Programming', 'kbk' => [3]],
            ['name' => 'Data Science', 'kbk' => [1]],
            ['name' => 'Natural Language Processing', 'kbk' => [1]],
            ['name' => 'Mobile dan Wireless Computing', 'kbk' => [2]],
            ['name' => 'Teknologi Open Source', 'kbk' => [2]],
            ['name' => 'Komersialisasi Produk informatika', 'kbk' => [3]],
            ['name' => 'Business Intelegence', 'kbk' => [1]],
        ])->each(function ($course) {
            $c = Course::query()->create(['name' => $course['name']]);

            $c->experts()->sync($course['kbk']);
        });

        $this->command->info('Finish seeding courses');

        return $this;
    }

    public function userSeed(): self
    {
        $users = collect([[
            'name' => 'Charis Saida Mukmin',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B+'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'B+'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Alvian',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer	', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B+'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Andhika',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'C'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'E'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'D'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B+'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'B-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B+'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'B-'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'B+'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Metodologi Penelitian', 'score' => 'B+'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'B+'],
                ['course' => 'Kewirausahaan', 'score' => 'B'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Akbar',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'B+'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'A-'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Krisma',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B-'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B+'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'B+'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B+'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B-'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A-'],
            ],
        ], [
            'name' => 'Septa',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'B+'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'B'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B+'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B+'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B+'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'A-'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A-'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Robaith',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B-'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B+'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B-'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Virga',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B-'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A'],
                ['course' => 'Multimedia', 'score' => 'A'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B+'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'A'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Frans',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'B+'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A-'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B+'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'B+'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Hilham',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'B-'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B+'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'B+'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B-'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'C'],
                ['course' => 'Struktur Data', 'score' => 'B-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'C'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'E'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'B+'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B+'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B-'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Galih',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Protestan', 'score' => 'B+'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B+'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B+'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'B-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A-'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Shofin',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B+'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'B+'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B+'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'A'],
                ['course' => 'Game Programming', 'score' => 'A-'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Styo',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B+'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A'],
                ['course' => 'Struktur Data', 'score' => 'B+'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'B'],
                ['course' => 'Multimedia', 'score' => 'B+'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'B+'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B+'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B+'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Refan',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B+'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B+'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'B+'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'B'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'B+'],
                ['course' => 'Multimedia', 'score' => 'B+'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B-'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Alif',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'B+'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'B'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'B'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'B-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'E'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'B+'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B+'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B-'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
            ],
        ], [
            'name' => 'Bhisma',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B+'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'B+'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], ]);

        User::factory($users->count())
        ->sequence(fn (Sequence $sequence) => ['name' => $users[$sequence->index]['name']])
        ->create()
        ->each(function (User $user, int $index) use ($users) {
            $current = collect($users[$index]['results']);

            $courses = Course::query()->whereIn('name', $current->pluck('course')->toArray())->get();
            $user->courses()->sync(
                $courses->mapWithKeys(fn (Course $course) => [
                    $course->id => [
                        'score' => $current->firstWhere('course', $course->name)['score'],
                    ],
                ])->toArray()
            );
        });

        $this->command->info('Finish seeding users');

        return $this;
    }
}
