<?php

namespace App\Http\Controllers;

use Algorithm\C45;
use Algorithm\C45\DataInput;
use App\Models\Course;
use App\Models\Expert;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Rubix\ML\Classifiers\KNearestNeighbors;
use Rubix\ML\Classifiers\NaiveBayes;
use Rubix\ML\Datasets\Labeled;
use Rubix\ML\Datasets\Unlabeled;
use Rubix\ML\Extractors\CSV;

class TrainingController extends Controller
{
    /* public function __invoke(Request $request)
    {
        $users = collect([[
            'name' => 'Charis Saida Mukmin',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B+'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'B+'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Alvian',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer	', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => '	A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B+'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Andhika',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'C'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'E'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'D'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B+'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'B-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B+'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'B-'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'B+'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Metodologi Penelitian', 'score' => 'B+'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'B+'],
                ['course' => 'Kewirausahaan', 'score' => 'B'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Akbar',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'B+'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'A-'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Krisma',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B-'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B+'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'B+'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B+'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B-'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A-'],
            ],
        ], [
            'name' => 'Septa',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'B+'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'B'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B+'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B+'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B+'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'A-'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A-'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Robaith',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B-'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B+'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B-'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Virga',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B-'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A'],
                ['course' => 'Multimedia', 'score' => 'A'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B+'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'A'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Frans',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A-'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'B+'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A-'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B+'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'B+'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Hilham',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'B-'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B+'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'B+'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'B+'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B-'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'C'],
                ['course' => 'Struktur Data', 'score' => 'B-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'C'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'E'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'B+'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B+'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B-'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Galih',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Protestan', 'score' => 'B+'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B+'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'B+'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'B-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A-'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A-'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Shofin',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B+'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B'],
                ['course' => 'Struktur Data', 'score' => 'A-'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'B+'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B+'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'A'],
                ['course' => 'Game Programming', 'score' => 'A-'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], [
            'name' => 'Styo',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B+'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'A-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A'],
                ['course' => 'Struktur Data', 'score' => 'B+'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'B'],
                ['course' => 'Multimedia', 'score' => 'B+'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritrna', 'score' => 'B+'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B+'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B+'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A'],
                ['course' => 'Kewirausahaan', 'score' => 'B'],
                ['course' => 'GameProgramming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'B+'],
                ['course' => 'Natural Language Processing', 'score' => 'A'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Refan',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'B+'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B+'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'B+'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'B'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'B+'],
                ['course' => 'Multimedia', 'score' => 'B+'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'A'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Komersialisasi Produk informatika', 'score' => 'B'],
                ['course' => 'Business Intelegence', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B-'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
            ],
        ], [
            'name' => 'Alif',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'B+'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A-'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A-'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B-'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'A'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'A-'],
                ['course' => 'Struktur Data', 'score' => 'B'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'B-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'B'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'B-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'E'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'B+'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'B+'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'A-'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B-'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A-'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A-'],
            ],
        ], [
            'name' => 'Bhisma',
            'results' => [
                ['course' => 'Bahasa Inggris Profesi', 'score' => 'A'],
                ['course' => 'Kesehatan dan Keselamatan Kerja (K3)', 'score' => 'A'],
                ['course' => 'Matematika Komputer 1', 'score' => 'A'],
                ['course' => 'Pengantar Teknologi Informasi', 'score' => 'A'],
                ['course' => 'Algoritma dan Pemrograman', 'score' => 'A'],
                ['course' => 'Basis Data dan Sistem Informasi', 'score' => 'B'],
                ['course' => 'Organisasi dan Arsitektur Komputer', 'score' => 'A-'],
                ['course' => 'Pendidikan Agama Islam', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 2', 'score' => 'A'],
                ['course' => 'Pemrograman Berorientasi Obyek', 'score' => 'B'],
                ['course' => 'Komunikasi Data dan Jaringan Komputer', 'score' => 'B+'],
                ['course' => 'Struktur Data', 'score' => 'B+'],
                ['course' => 'Probabilitas dan Statistik', 'score' => 'A-'],
                ['course' => 'Pemrograman Web', 'score' => 'A'],
                ['course' => 'Pendidikan Kewarganegaraan', 'score' => 'A-'],
                ['course' => 'Pendidikan Pancasila', 'score' => 'A-'],
                ['course' => 'Matematika Komputer 3', 'score' => 'A'],
                ['course' => 'Rekayasa Perangkat Lunak', 'score' => 'A-'],
                ['course' => 'Sistem Operasi', 'score' => 'A'],
                ['course' => 'Grafika Komputer', 'score' => 'A'],
                ['course' => 'Pemrograman Deklaratif', 'score' => 'A-'],
                ['course' => 'Interaksi Manusia dan Komputer', 'score' => 'A'],
                ['course' => 'Manajemen Inovasi', 'score' => 'A'],
                ['course' => 'Pendidikan Bahasa Indonesia', 'score' => 'A'],
                ['course' => 'Multimedia', 'score' => 'A-'],
                ['course' => 'Proyek Sistem Informasi', 'score' => 'A'],
                ['course' => 'Analisis dan Desain Algoritma', 'score' => 'B+'],
                ['course' => 'Sosioteknologi Informatika', 'score' => 'A-'],
                ['course' => 'Keamanan Jaringan & Kriptografi', 'score' => 'A-'],
                ['course' => 'Kecerdasan Buatan', 'score' => 'B'],
                ['course' => 'Internet of things (IoT)', 'score' => 'A'],
                ['course' => 'Educational Informatics', 'score' => 'A'],
                ['course' => 'Metodologi Penelitian', 'score' => 'A-'],
                ['course' => 'Kewirausahaan', 'score' => 'B+'],
                ['course' => 'Game Programming', 'score' => 'A'],
                ['course' => 'Data Science', 'score' => 'A-'],
                ['course' => 'Natural Language Processing', 'score' => 'A'],
                ['course' => 'Mobile dan Wireless Computing', 'score' => 'A'],
                ['course' => 'Teknologi Open Source', 'score' => 'A'],
            ],
        ], ]);

        dd($users->pluck('results')->sum(fn ($result) => count($result)));

        collect([
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Educational Informatics',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Pendidikan Kewarganegaraan',
            'Metodologi Penelitian',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Educational Informatics',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Komersialisasi Produk informatika',
            'Business Intelegence',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Internet of things (IoT)',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Komersialisasi Produk informatika',
            'Business Intelegence',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Internet of things (IoT)',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Komersialisasi Produk informatika',
            'Business Intelegence',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Internet of things (IoT)',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Komersialisasi Produk informatika',
            'Business Intelegence',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Internet of things (IoT)',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Pendidikan Kewarganegaraan',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Educational Informatics',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Protestan',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Pendidikan Kewarganegaraan',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Educational Informatics',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Komersialisasi Produk informatika',
            'Business Intelegence',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Internet of things (IoT)',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Komersialisasi Produk informatika',
            'Business Intelegence',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Internet of things (IoT)',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Educational Informatics',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
            'Pendidikan Bahasa Indonesia',
            'Bahasa Inggris Profesi',
            'Kesehatan dan Keselamatan Kerja (K3)',
            'Matematika Komputer 1',
            'Pengantar Teknologi Informasi',
            'Algoritma dan Pemrograman',
            'Basis Data dan Sistem Informasi',
            'Organisasi dan Arsitektur Komputer',
            'Pendidikan Agama Islam',
            'Matematika Komputer 2',
            'Pemrograman Berorientasi Obyek',
            'Komunikasi Data dan Jaringan Komputer',
            'Struktur Data',
            'Probabilitas dan Statistik',
            'Pemrograman Web',
            'Pendidikan Kewarganegaraan',
            'Pendidikan Pancasila',
            'Matematika Komputer 3',
            'Rekayasa Perangkat Lunak',
            'Sistem Operasi',
            'Grafika Komputer',
            'Pemrograman Deklaratif',
            'Interaksi Manusia dan Komputer',
            'Manajemen Inovasi',
            'Pendidikan Bahasa Indonesia',
            'Multimedia',
            'Proyek Sistem Informasi',
            'Analisis dan Desain Algoritma',
            'Sosioteknologi Informatika',
            'Keamanan Jaringan & Kriptografi',
            'Kecerdasan Buatan',
            'Internet of things (IoT)',
            'Educational Informatics',
            'Metodologi Penelitian',
            'Kewirausahaan',
            'Game Programming',
            'Data Science',
            'Natural Language Processing',
            'Mobile dan Wireless Computing',
            'Teknologi Open Source',
        ])
        ->unique()
        ->dd();
    } */
    /* public function __invoke(Request $request)
    {
        $dataset = Labeled::fromIterator(new CSV('file.csv'));

        [$training, $testing] = $dataset->stratifiedSplit(.8);

        $estimator = new NaiveBayes(/* priors: [
            'Correct' => .6,
            'Invalid' => .4,
        ], * smoothing: 2);

        $estimator->train($training);

        $predictions = $estimator->predict($dataset);

        dd($predictions);
        /* $user = User::query()
        ->with('courses.experts')
        ->first();

        $lectures = collect([]);

        foreach ($user->courses as $course) {
            foreach ($course->experts->pluck('name') as $expert) {
                $lectures->push([
                    'name' => $course->name,
                    'score' => $course->inNumber,
                    'expert' => $expert,
                ]);
            }
        }

        $this->estimate($lectures->toArray()); */

    // $user->lectures = $user->courses->map(fn (Course $course) => [
        //     'name' => $course->name,
        //     'score' => $course->inNumber,
        //     'experts' => $course->experts->pluck('name'),
    // ]);

    /* dd([
        'name' => $user->name,
        'courses' => $lectures,
    ]); *
    } */

    public function __invoke()
    {
        $c45 = new C45();
        $input = new DataInput;

        $input->setData($trainer = $this->trainer(8)->toArray());
        $input->setAttributes(
            Expert::query()->has('courses')->get()->pluck('name')->merge(['kbk'])->toArray()
        );

        $c45->c45 = $input;
        $c45->setTargetAttribute('kbk');
        $initialize = $c45->initialize();

        // output
        $buildTree = $initialize->buildTree();
        $arrayTree = $buildTree->toArray();
        $stringTree = $buildTree->toString();

        $testing = $this->testing(rand(1, 16));

        dd(
            $trainer,
            $testing,
            $stringTree,
            $c45->initialize()->buildTree()->classify($testing->toArray())
        );
    }

    private function trainer(int $limit = 3): Collection
    {
        return $this->query()
        ->inRandomOrder()
        ->limit($limit)
        ->get()
        ->map(function (User $user) {
            return $this->mapper($user);
        });
    }

    private function testing(int $searched)
    {
        $user = $this->query()
        ->find($searched);

        return $this->mapper($user, false);
    }

    private function mapper(User $user, bool $kbk = true): Collection
    {
        $courses = $user->courses->map(
            fn (Course $course) => $course->experts->pluck('name')
            ->map(fn (string $expert) => [
                'name' => $course->name,
                'score' => $course->inNumber,
                'expert' => $expert,
            ])
        )->flatten(1)
        ->groupBy('expert')
        ->map(function (Collection $expert) {
            return $expert->average('score');
        });

        if ($kbk) {
            $courses->put('kbk', $courses->search($courses->max()));
        }

        return $courses;
    }

    private function query(): Builder
    {
        return User::query()->with(['courses.experts']);
    }

    /* public function estimate(array $data)
    {
        $estimator = new KNearestNeighbors();

        // $dataset = new Unlabeled($data);

        $dataset = Labeled::fromIterator($data);

        $predictions = $estimator->predict($dataset);

        dd($predictions);
    } */
}
